# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_websitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='about',
            field=models.TextField(default='', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='description',
            field=models.CharField(default='this is test solo informations', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='favicon',
            field=models.ImageField(default='', height_field=30, upload_to='', width_field=30),
            preserve_default=False,
        ),
    ]
