# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
