# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20170506_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcomment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.Publication'),
        ),
    ]
